// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/layout/admin/admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QuantBotAdminClient is the client API for QuantBotAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuantBotAdminClient interface {
	PageBot(ctx context.Context, in *PageBotRequest, opts ...grpc.CallOption) (*PageBotReply, error)
	ListBot(ctx context.Context, in *ListBotRequest, opts ...grpc.CallOption) (*ListBotReply, error)
	GetBot(ctx context.Context, in *GetBotRequest, opts ...grpc.CallOption) (*GetBotReply, error)
	CreateBot(ctx context.Context, in *CreateBotRequest, opts ...grpc.CallOption) (*CreateBotReply, error)
	UpdateBot(ctx context.Context, in *UpdateBotRequest, opts ...grpc.CallOption) (*UpdateBotReply, error)
	DeleteBot(ctx context.Context, in *DeleteBotRequest, opts ...grpc.CallOption) (*DeleteBotReply, error)
}

type quantBotAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewQuantBotAdminClient(cc grpc.ClientConnInterface) QuantBotAdminClient {
	return &quantBotAdminClient{cc}
}

func (c *quantBotAdminClient) PageBot(ctx context.Context, in *PageBotRequest, opts ...grpc.CallOption) (*PageBotReply, error) {
	out := new(PageBotReply)
	err := c.cc.Invoke(ctx, "/api.layout.admin.QuantBotAdmin/PageBot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantBotAdminClient) ListBot(ctx context.Context, in *ListBotRequest, opts ...grpc.CallOption) (*ListBotReply, error) {
	out := new(ListBotReply)
	err := c.cc.Invoke(ctx, "/api.layout.admin.QuantBotAdmin/ListBot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantBotAdminClient) GetBot(ctx context.Context, in *GetBotRequest, opts ...grpc.CallOption) (*GetBotReply, error) {
	out := new(GetBotReply)
	err := c.cc.Invoke(ctx, "/api.layout.admin.QuantBotAdmin/GetBot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantBotAdminClient) CreateBot(ctx context.Context, in *CreateBotRequest, opts ...grpc.CallOption) (*CreateBotReply, error) {
	out := new(CreateBotReply)
	err := c.cc.Invoke(ctx, "/api.layout.admin.QuantBotAdmin/CreateBot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantBotAdminClient) UpdateBot(ctx context.Context, in *UpdateBotRequest, opts ...grpc.CallOption) (*UpdateBotReply, error) {
	out := new(UpdateBotReply)
	err := c.cc.Invoke(ctx, "/api.layout.admin.QuantBotAdmin/UpdateBot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quantBotAdminClient) DeleteBot(ctx context.Context, in *DeleteBotRequest, opts ...grpc.CallOption) (*DeleteBotReply, error) {
	out := new(DeleteBotReply)
	err := c.cc.Invoke(ctx, "/api.layout.admin.QuantBotAdmin/DeleteBot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuantBotAdminServer is the server API for QuantBotAdmin service.
// All implementations must embed UnimplementedQuantBotAdminServer
// for forward compatibility
type QuantBotAdminServer interface {
	PageBot(context.Context, *PageBotRequest) (*PageBotReply, error)
	ListBot(context.Context, *ListBotRequest) (*ListBotReply, error)
	GetBot(context.Context, *GetBotRequest) (*GetBotReply, error)
	CreateBot(context.Context, *CreateBotRequest) (*CreateBotReply, error)
	UpdateBot(context.Context, *UpdateBotRequest) (*UpdateBotReply, error)
	DeleteBot(context.Context, *DeleteBotRequest) (*DeleteBotReply, error)
	mustEmbedUnimplementedQuantBotAdminServer()
}

// UnimplementedQuantBotAdminServer must be embedded to have forward compatible implementations.
type UnimplementedQuantBotAdminServer struct {
}

func (UnimplementedQuantBotAdminServer) PageBot(context.Context, *PageBotRequest) (*PageBotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageBot not implemented")
}
func (UnimplementedQuantBotAdminServer) ListBot(context.Context, *ListBotRequest) (*ListBotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBot not implemented")
}
func (UnimplementedQuantBotAdminServer) GetBot(context.Context, *GetBotRequest) (*GetBotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBot not implemented")
}
func (UnimplementedQuantBotAdminServer) CreateBot(context.Context, *CreateBotRequest) (*CreateBotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBot not implemented")
}
func (UnimplementedQuantBotAdminServer) UpdateBot(context.Context, *UpdateBotRequest) (*UpdateBotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBot not implemented")
}
func (UnimplementedQuantBotAdminServer) DeleteBot(context.Context, *DeleteBotRequest) (*DeleteBotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBot not implemented")
}
func (UnimplementedQuantBotAdminServer) mustEmbedUnimplementedQuantBotAdminServer() {}

// UnsafeQuantBotAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuantBotAdminServer will
// result in compilation errors.
type UnsafeQuantBotAdminServer interface {
	mustEmbedUnimplementedQuantBotAdminServer()
}

func RegisterQuantBotAdminServer(s grpc.ServiceRegistrar, srv QuantBotAdminServer) {
	s.RegisterService(&QuantBotAdmin_ServiceDesc, srv)
}

func _QuantBotAdmin_PageBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantBotAdminServer).PageBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.layout.admin.QuantBotAdmin/PageBot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantBotAdminServer).PageBot(ctx, req.(*PageBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantBotAdmin_ListBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantBotAdminServer).ListBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.layout.admin.QuantBotAdmin/ListBot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantBotAdminServer).ListBot(ctx, req.(*ListBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantBotAdmin_GetBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantBotAdminServer).GetBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.layout.admin.QuantBotAdmin/GetBot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantBotAdminServer).GetBot(ctx, req.(*GetBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantBotAdmin_CreateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantBotAdminServer).CreateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.layout.admin.QuantBotAdmin/CreateBot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantBotAdminServer).CreateBot(ctx, req.(*CreateBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantBotAdmin_UpdateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantBotAdminServer).UpdateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.layout.admin.QuantBotAdmin/UpdateBot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantBotAdminServer).UpdateBot(ctx, req.(*UpdateBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuantBotAdmin_DeleteBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuantBotAdminServer).DeleteBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.layout.admin.QuantBotAdmin/DeleteBot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuantBotAdminServer).DeleteBot(ctx, req.(*DeleteBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuantBotAdmin_ServiceDesc is the grpc.ServiceDesc for QuantBotAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuantBotAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.layout.admin.QuantBotAdmin",
	HandlerType: (*QuantBotAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PageBot",
			Handler:    _QuantBotAdmin_PageBot_Handler,
		},
		{
			MethodName: "ListBot",
			Handler:    _QuantBotAdmin_ListBot_Handler,
		},
		{
			MethodName: "GetBot",
			Handler:    _QuantBotAdmin_GetBot_Handler,
		},
		{
			MethodName: "CreateBot",
			Handler:    _QuantBotAdmin_CreateBot_Handler,
		},
		{
			MethodName: "UpdateBot",
			Handler:    _QuantBotAdmin_UpdateBot_Handler,
		},
		{
			MethodName: "DeleteBot",
			Handler:    _QuantBotAdmin_DeleteBot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/layout/admin/admin.proto",
}
