// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/layout/v1/api.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ChainBotWebHookRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ChainBotWebHookRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChainBotWebHookRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ChainBotWebHookRequestMultiError, or nil if none found.
func (m *ChainBotWebHookRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ChainBotWebHookRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ChainBotWebHookRequestMultiError(errors)
	}

	return nil
}

// ChainBotWebHookRequestMultiError is an error wrapping multiple validation
// errors returned by ChainBotWebHookRequest.ValidateAll() if the designated
// constraints aren't met.
type ChainBotWebHookRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChainBotWebHookRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChainBotWebHookRequestMultiError) AllErrors() []error { return m }

// ChainBotWebHookRequestValidationError is the validation error returned by
// ChainBotWebHookRequest.Validate if the designated constraints aren't met.
type ChainBotWebHookRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChainBotWebHookRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChainBotWebHookRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChainBotWebHookRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChainBotWebHookRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChainBotWebHookRequestValidationError) ErrorName() string {
	return "ChainBotWebHookRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ChainBotWebHookRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChainBotWebHookRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChainBotWebHookRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChainBotWebHookRequestValidationError{}

// Validate checks the field values on ChainBotWebHookReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ChainBotWebHookReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChainBotWebHookReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ChainBotWebHookReplyMultiError, or nil if none found.
func (m *ChainBotWebHookReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ChainBotWebHookReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ChainBotWebHookReplyMultiError(errors)
	}

	return nil
}

// ChainBotWebHookReplyMultiError is an error wrapping multiple validation
// errors returned by ChainBotWebHookReply.ValidateAll() if the designated
// constraints aren't met.
type ChainBotWebHookReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChainBotWebHookReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChainBotWebHookReplyMultiError) AllErrors() []error { return m }

// ChainBotWebHookReplyValidationError is the validation error returned by
// ChainBotWebHookReply.Validate if the designated constraints aren't met.
type ChainBotWebHookReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChainBotWebHookReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChainBotWebHookReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChainBotWebHookReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChainBotWebHookReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChainBotWebHookReplyValidationError) ErrorName() string {
	return "ChainBotWebHookReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ChainBotWebHookReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChainBotWebHookReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChainBotWebHookReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChainBotWebHookReplyValidationError{}
