service:
  name: layout
  version: v1.0.0
server:
  http:
    address: 0.0.0.0:8034
    timeout: 1000s
  grpc:
    address: 0.0.0.0:9034
    timeout: 1000s
data:
  order:
    driver: sqlite
    source: "../../data/order.db"
    logLevel: 4
    db: layout
    timeout: 10s
  kline:
    driver: sqlite
    source: "../../data/kline.db"
    logLevel: 4
    db: layout
    timeout: 10s
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 0.1s
    read_timeout: 0.2s
    write_timeout: 0.2s
  migrate:
    path: file://../../migrations
reg:
  etcd:
    enable: false
    endpoints:
      - "127.0.0.1:2379"
    dialTimeout: 3s
  consul:
    enable: false
    address: "127.0.0.1:8500"
    dialTimeout: 3s
  kube:
    enable: false
  nacos:
    enable: true
    ipAddr: nacos-test.music-z.com
    port: 80
    namespace: 40da457f-331b-4090-9f7f-6888ea5451e0
trace:
  stdout:
    enable: true
    traces: true
    trace_output: no
    metrics: true
    metric_output: no
  jaeger:
    enable: false
    endpoint: http://127.0.0.1:14268/api/traces
  otlp:
    enable: false
  prom:
    enable: false
logger:
  console:
    enable: true
    level: -1
  file:
    enable: false
    level: -1
    path: ../../logs
  fluent:
    enable: false
rabbitMq:
  address: amqp://admin:123456@127.0.0.1:5672/my_vhost
  consumer:
    queue:
      - xx
