// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/helloworld/v1/api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LayoutV1Client is the client API for LayoutV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LayoutV1Client interface {
	ChainBotWebHook(ctx context.Context, in *ChainBotWebHookRequest, opts ...grpc.CallOption) (*ChainBotWebHookReply, error)
}

type layoutV1Client struct {
	cc grpc.ClientConnInterface
}

func NewLayoutV1Client(cc grpc.ClientConnInterface) LayoutV1Client {
	return &layoutV1Client{cc}
}

func (c *layoutV1Client) ChainBotWebHook(ctx context.Context, in *ChainBotWebHookRequest, opts ...grpc.CallOption) (*ChainBotWebHookReply, error) {
	out := new(ChainBotWebHookReply)
	err := c.cc.Invoke(ctx, "/api.helloworld.v1.LayoutV1/ChainBotWebHook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LayoutV1Server is the server API for LayoutV1 service.
// All implementations must embed UnimplementedLayoutV1Server
// for forward compatibility
type LayoutV1Server interface {
	ChainBotWebHook(context.Context, *ChainBotWebHookRequest) (*ChainBotWebHookReply, error)
	mustEmbedUnimplementedLayoutV1Server()
}

// UnimplementedLayoutV1Server must be embedded to have forward compatible implementations.
type UnimplementedLayoutV1Server struct {
}

func (UnimplementedLayoutV1Server) ChainBotWebHook(context.Context, *ChainBotWebHookRequest) (*ChainBotWebHookReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChainBotWebHook not implemented")
}
func (UnimplementedLayoutV1Server) mustEmbedUnimplementedLayoutV1Server() {}

// UnsafeLayoutV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LayoutV1Server will
// result in compilation errors.
type UnsafeLayoutV1Server interface {
	mustEmbedUnimplementedLayoutV1Server()
}

func RegisterLayoutV1Server(s grpc.ServiceRegistrar, srv LayoutV1Server) {
	s.RegisterService(&LayoutV1_ServiceDesc, srv)
}

func _LayoutV1_ChainBotWebHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainBotWebHookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutV1Server).ChainBotWebHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.helloworld.v1.LayoutV1/ChainBotWebHook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutV1Server).ChainBotWebHook(ctx, req.(*ChainBotWebHookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LayoutV1_ServiceDesc is the grpc.ServiceDesc for LayoutV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LayoutV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.helloworld.v1.LayoutV1",
	HandlerType: (*LayoutV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChainBotWebHook",
			Handler:    _LayoutV1_ChainBotWebHook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/helloworld/v1/api.proto",
}
