// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCexBinanceKlineCsv = "cex_binance_kline_csv"

// CexBinanceKlineCsv mapped from table <cex_binance_kline_csv>
type CexBinanceKlineCsv struct {
	ID        int64          `gorm:"column:id;primaryKey" json:"id"`
	Event     string         `gorm:"column:event;not null" json:"event"`
	Symbol    string         `gorm:"column:symbol;not null" json:"symbol"`
	Interval  string         `gorm:"column:interval;not null" json:"interval"`
	StartTime int64          `gorm:"column:start_time;not null" json:"start_time"`
	EndTime   int64          `gorm:"column:end_time;not null" json:"end_time"`
	File      string         `gorm:"column:file;not null" json:"file"`
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;not null" json:"deleted_at"`
}

// TableName CexBinanceKlineCsv's table name
func (*CexBinanceKlineCsv) TableName() string {
	return TableNameCexBinanceKlineCsv
}
