// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameChainbotBot = "chainbot_bot"

// ChainbotBot mapped from table <chainbot_bot>
type ChainbotBot struct {
	ID             int64          `gorm:"column:id;primaryKey" json:"id"`
	BotID          string         `gorm:"column:bot_id;not null" json:"bot_id"`
	SubID          string         `gorm:"column:sub_id;not null" json:"sub_id"`
	DriverType     string         `gorm:"column:driver_type;not null" json:"driver_type"`
	NotifyTemplate string         `gorm:"column:notify_template;not null" json:"notify_template"`
	TemplateID     int64          `gorm:"column:template_id;not null" json:"template_id"`
	CreatedAt      time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;not null" json:"deleted_at"`
}

// TableName ChainbotBot's table name
func (*ChainbotBot) TableName() string {
	return TableNameChainbotBot
}
